# Numpy

## 1. Array
## 2. 1D,2D,3D Array


In [1]:
import numpy as np

In [2]:
A1 = np.array([1,2,3,4])

In [3]:
A1

array([1, 2, 3, 4])

In [4]:
print(A1)

[1 2 3 4]


In [5]:
type(A1)

numpy.ndarray

In [6]:
A1.shape

(4,)

In [7]:
A1.size

4

In [8]:
A1.ndim

1

In [9]:
len(A1)

4

-------------------

In [10]:
A2 = np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
A2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
type(A2)

numpy.ndarray

In [14]:
A2.shape

(2, 4)

In [15]:
A2.size

8

In [16]:
A2.ndim

2

In [17]:
len(A2)

2

In [18]:
A1.ndim

1

---------

In [19]:
a3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [20]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [21]:
print(a3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [22]:
a3.ndim

3

In [23]:
type(a3)

numpy.ndarray

In [24]:
a3.shape

(1, 3, 4)

In [25]:
a3.size

12

In [26]:
len(a3)

1

---------------------

# Zeros Array - An array in which all values are 0.

### ZA = np.zeros(shape, dtype)

- We can define the shape and data-type of zeros array.
- We can create 1-D, 2-D, as well 3-D zeros array.
- The default data-type is float.

* ndim - to check the dimension of the array
* shape - to check the shape of the array
* size - to check the size of the array

In [27]:
z1 = np.zeros(3)

In [28]:
z1 

array([0., 0., 0.])

In [29]:
print(z1)

[0. 0. 0.]


In [30]:
z1 = np.zeros(5, dtype = int)

In [31]:
z1

array([0, 0, 0, 0, 0])

In [32]:
print(z1)

[0 0 0 0 0]


In [33]:
type(z1)

numpy.ndarray

In [34]:
z1.ndim

1

In [35]:
np.ndim(z1)

1

---------------

In [36]:
z2 = np.zeros((3,4))

In [37]:
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
print(z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
z2 = np.zeros((3,4), dtype = int)

In [40]:
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
print(z2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [42]:
z2.shape

(3, 4)

In [43]:
z2.size

12

In [44]:
len(z2)

3

-------------

In [45]:
z3 = np.zeros((2,3,4))

In [46]:
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
print(z3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [48]:
z3 = np.zeros((2,3,4), dtype = int)

In [49]:
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [50]:
print(z3)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [51]:
z3.ndim

3

In [52]:
z3.size

24

In [53]:
len(z3)

2

In [54]:
z3.shape

(2, 3, 4)

----------------

# Ones Array - An array in which all values are 1.

### A = np.ones(shape, dtype)

- We can define the shape and data-type of ones array.
- We can create 1-D, 2-D, as well 3-D ones array.
- The default data-type is float.

* ndim - to check the dimension of the array
* shape - to check the shape of the array
* size - to check the size of the array

In [55]:
np.ones(3)

array([1., 1., 1.])

In [56]:
q1 = np.ones(3, dtype = int)

In [57]:
q1

array([1, 1, 1])

In [58]:
print(q1)

[1 1 1]


In [59]:
q1.shape

(3,)

In [60]:
q1.ndim

1

In [61]:
np.ndim(q1)

1

In [62]:
type(q1)

numpy.ndarray

In [63]:
q1.size

3

In [64]:
len(q1)

3

-----------------

In [65]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
q2 = np.ones((2,3), dtype = int)

In [67]:
q2

array([[1, 1, 1],
       [1, 1, 1]])

In [68]:
print(q2)

[[1 1 1]
 [1 1 1]]


In [69]:
q2.shape

(2, 3)

In [70]:
q2.ndim

2

In [71]:
q2.size

6

In [72]:
len(q2)

2

----------------

In [73]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [74]:
q3 = np.ones((2,3,4), dtype = int)

In [75]:
q3

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [76]:
print(q3)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [77]:
q3.shape

(2, 3, 4)

In [78]:
q3.ndim

3

In [79]:
q3.size

24

In [80]:
len(q3)

2

---------------------------

# Full Array - An array in which all values are same (constant)

### F = np.full(shape, fill_value)

- We can define the shape, and pass the value to be filled in the 'Full Arrays'.
- We can create 1-D, 2-D, as well as 3-D Full Array, with integer, float or string values.
- The default data-type is Integer.

* ndim - to check the dimension of the array
* shape - to check the shape of the array
* size - to check the size of the array

In [81]:
np.full(3, 79)

array([79, 79, 79])

In [82]:
f1 = np.full(3, 79)

In [83]:
f1

array([79, 79, 79])

In [84]:
print(f1)

[79 79 79]


In [85]:
np.full(3, 69.69)

array([69.69, 69.69, 69.69])

In [86]:
np.full(3, 69, dtype = float)

array([69., 69., 69.])

In [87]:
np.full(3, 69, float)

array([69., 69., 69.])

In [88]:
f1.ndim

1

In [89]:
np.ndim(f1)

1

--------------------------

In [90]:
np.full((2,3), 88)

array([[88, 88, 88],
       [88, 88, 88]])

In [91]:
f2 = np.full((3,3), 50.9)
f2

array([[50.9, 50.9, 50.9],
       [50.9, 50.9, 50.9],
       [50.9, 50.9, 50.9]])

In [92]:
np.ndim(f2)

2

In [93]:
f2 = np.full((2,2), 523, str)

In [94]:
f2

array([['5', '5'],
       ['5', '5']], dtype='<U1')

In [95]:
print(f2)

[['5' '5']
 ['5' '5']]


In [96]:
f2 = np.full((2,2), "hi")

In [97]:
f2

array([['hi', 'hi'],
       ['hi', 'hi']], dtype='<U2')

In [98]:
f2.shape

(2, 2)

---------------

In [99]:
np.full([2,3,4], "python", str)

array([[['p', 'p', 'p', 'p'],
        ['p', 'p', 'p', 'p'],
        ['p', 'p', 'p', 'p']],

       [['p', 'p', 'p', 'p'],
        ['p', 'p', 'p', 'p'],
        ['p', 'p', 'p', 'p']]], dtype='<U1')

In [100]:
np.full([2,3,4], "python")

array([[['python', 'python', 'python', 'python'],
        ['python', 'python', 'python', 'python'],
        ['python', 'python', 'python', 'python']],

       [['python', 'python', 'python', 'python'],
        ['python', 'python', 'python', 'python'],
        ['python', 'python', 'python', 'python']]], dtype='<U6')

In [101]:
f3 =np.full([2,3,4], "python")
f3.shape

(2, 3, 4)

In [102]:
f3.ndim

3

In [103]:
f3.size

24

In [104]:
len(f3)

2

----------------

# The Random Module contain the functions which are used for generating random numbers.

In [105]:
import numpy as np
from numpy import random

## 1. Random Function

It returns random float number(s) between 0 and 1.

In [106]:
np.random.random()

0.6496925915932333

In [107]:
np.random.random(4)

array([0.65952447, 0.95948667, 0.99143036, 0.60220717])

In [108]:
np.random.random((2,3))

array([[0.97546818, 0.8714391 , 0.97770104],
       [0.94532464, 0.57731682, 0.79824327]])

In [109]:
np.random.random((2,3,5))

array([[[0.01698977, 0.49517997, 0.67423248, 0.09704033, 0.1878764 ],
        [0.14501372, 0.08630788, 0.35219904, 0.81055187, 0.28203268],
        [0.9211476 , 0.17225123, 0.35436266, 0.21506296, 0.46559816]],

       [[0.57009361, 0.53237524, 0.35150627, 0.83245578, 0.7611184 ],
        [0.69820678, 0.47643518, 0.93826991, 0.28787352, 0.49533348],
        [0.17952528, 0.02754404, 0.08163195, 0.78841322, 0.15969973]]])

---------------------------

#### 2. Randint Function
- It generates random integer number(s) between given range. 
- By default, the range starts from 0.
- The numbers can repeat.

In [110]:
np.random.randint(2,13)

11

In [111]:
np.random.randint(2,13,5)

array([ 6, 12, 11, 11,  6])

In [112]:
np.random.randint(5)

4

--------------------------

## 3. Rand Function

It returns random float number(s) between 0 and 1.

In [113]:
np.random.rand()

0.39025441517877235

In [114]:
np.random.rand(4)

array([0.60413036, 0.24953191, 0.02658507, 0.85960857])

In [115]:
np.random.rand(2,3)

array([[0.4481126 , 0.65576132, 0.03478523],
       [0.44748106, 0.29542084, 0.68289398]])

In [116]:
np.random.rand(2,3,5)

array([[[0.54471539, 0.8758534 , 0.30511157, 0.97831983, 0.44259971],
        [0.0773027 , 0.16491556, 0.07543474, 0.49319018, 0.58711887],
        [0.36483401, 0.6591038 , 0.49162454, 0.4247582 , 0.80700444]],

       [[0.74196961, 0.91733581, 0.33325038, 0.33964203, 0.61022808],
        [0.98016621, 0.92444942, 0.02923255, 0.43943279, 0.71418618],
        [0.06440454, 0.14749146, 0.5268325 , 0.45983494, 0.27082231]]])

---

## 4. Randn Function

It returns random float numbers (postive and negative both) in the form of array.

In [117]:
np.random.randn()

0.5523971824379835

In [118]:
np.random.randn(2,3)

array([[ 0.01753058,  0.525303  ,  0.46634891],
       [ 1.41566681,  0.32984581, -1.29648228]])

In [119]:
np.random.randn(2,3,3)

array([[[-1.18347901, -0.34641168, -0.33876517],
        [ 1.0605594 ,  0.76100392,  1.96899793],
        [-0.42394581,  0.09123886,  0.53449957]],

       [[-0.412219  , -0.46685248, -0.17520724],
        [-0.46553503,  0.80223161,  0.08981845],
        [ 0.88841308,  0.9848473 , -0.94971114]]])

In [120]:
np.random.randn(3)

array([ 0.53299813,  1.56678803, -0.5074623 ])

---

## 5. Uniform Function

- It returns random float number(s) between the given range of values.
- The random numbers can't repeat.
- By default, the range starts from 0.
- If nothing is passed in (), it will return a float number between 0 and 1.

In [121]:
np.random.uniform(2,5)

3.2491295646597718

In [122]:
np.random.uniform(2,5,17)

array([3.15657423, 3.74744205, 2.75388923, 2.82772884, 2.44017413,
       2.88641257, 4.94632296, 4.55010888, 3.84480733, 4.42356944,
       3.94786177, 3.62341296, 2.34082858, 2.23587654, 3.18298637,
       4.00624731, 3.97806157])

In [123]:
np.random.uniform(5)

4.742804579923764

In [124]:
np.random.uniform()

0.4713395556825606

In [125]:
np.random.uniform((2,3,4),5)

array([4.12374443, 4.92894473, 4.59508041])

----

## 6. Choice Function
- It returns random integer number(s) from the given sequence.
- The range starts from 0 by default.
- If only 1 element is passed, then it will return a number between 0 and that element.
- By default, replace = True , which means the numbers can repeat.

In [126]:
np.random.choice([1,2,3,464,6,51,6,16,65])

51

In [127]:
np.random.choice([2,5,6,8,4,6,3,1,4,45,78,65,21,645,98], 5)

array([98,  4,  1,  2,  5])

In [128]:
np.random.choice(13,123)

array([ 4,  9, 11,  4,  2, 12,  8, 10,  0,  8, 11, 10,  2,  1,  7,  1,  3,
        8,  3,  6,  7,  8,  3,  0,  9, 12,  9,  7, 11,  0,  1,  9, 11, 11,
       12,  5,  8,  4, 12,  8,  3,  5, 11,  8,  8,  9,  9,  9,  0,  6,  6,
       12,  6, 11,  3,  5,  2,  8,  8,  1,  2,  6, 11,  4,  5,  8,  9, 11,
        1,  5, 11, 11,  6,  2, 10, 11,  6,  6,  3,  1,  8,  4,  5,  8,  0,
       10,  3,  6,  7,  1,  3,  8,  8, 11,  0,  9,  4,  4,  7,  0,  6, 12,
        8,  2, 10,  7, 11, 12,  0,  0,  3, 11,  6,  2,  0, 11, 12, 10, 11,
       12, 10,  6,  5])

In [129]:
np.random.choice([1,2,3,4,5,6,7,8,9,11,22,33,44,55,66,77,88,99,100], size = 5, replace = False)

array([ 2, 44, 11, 33,  7])

In [130]:
np.random.choice(7)

2

----

# Linspace Function returns evenly(linearly) spaced values within a given interval


### np.linspace(start_value, stop_value, num=50, endpoint=False, retstep=True, dtype=None)



##### Note - By Default it shows 50 values

--------

In [131]:
w = np.linspace(2, 20, num = 10)

In [132]:
w

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [133]:
print(w)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [134]:
w = np.linspace(2, 20, num = 5)

In [135]:
w

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [136]:
w = np.linspace(2, 20, num=10, endpoint=False)

In [137]:
print(w)

[ 2.   3.8  5.6  7.4  9.2 11.  12.8 14.6 16.4 18.2]


In [138]:
w = np.linspace(2, 20, num=10, endpoint=True)

In [139]:
print(w)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [140]:
w = np.linspace(2, 20, num=10, endpoint=True, retstep=True)

In [141]:
print(w)

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)


In [142]:
w = np.linspace(2, 20, num=10, endpoint=True, retstep=False)

In [143]:
print(w)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [144]:
w = np.linspace(2, 20, num=10, endpoint=True, retstep=False, dtype = int)

In [145]:
print(w)

[ 2  4  6  8 10 12 14 16 18 20]


In [146]:
w = np.linspace(2, 20, num=10, endpoint=True, retstep=False, dtype = str)
print(w)

['2.0' '4.0' '6.0' '8.0' '10.0' '12.0' '14.0' '16.0' '18.0' '20.0']


In [147]:
w = np.linspace(2,20)

In [148]:
print(w)

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]


In [149]:
w = np.linspace(2, 20, num=24, retstep=True)
print(w)

(array([ 2.        ,  2.7826087 ,  3.56521739,  4.34782609,  5.13043478,
        5.91304348,  6.69565217,  7.47826087,  8.26086957,  9.04347826,
        9.82608696, 10.60869565, 11.39130435, 12.17391304, 12.95652174,
       13.73913043, 14.52173913, 15.30434783, 16.08695652, 16.86956522,
       17.65217391, 18.43478261, 19.2173913 , 20.        ]), 0.782608695652174)


------------------

## Empty Function is used to create an array of arbitary values, of given shape and datatype, without initializing the entries.


### Syntax : np.empty(shape, dtype)


* Shape can given in list or tuple form
* The Default datatype is float

In [150]:
np.empty(shape=5, dtype=int)

array([302983056,       398,         0,         0,         1])

In [151]:
a = np.empty(5)

In [152]:
a

array([8.48798316e-314, 1.69759663e-313, 2.54639495e-313, 3.39519327e-313,
       4.24399158e-313])

In [153]:
a = np.empty(5, dtype = int)

In [154]:
a

array([302983056,       398,         0,         0,         1])

In [155]:
np.empty(5, dtype = object)

array([None, None, None, None, None], dtype=object)

In [156]:
b = np.empty((5, 3))

In [157]:
b

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.00068841e+296]])

In [158]:
b = np.empty((5,3), dtype=int)

In [159]:
b

array([[  2,   5,   6],
       [  8,   4,   6],
       [  3,   1,   4],
       [ 45,  78,  65],
       [ 21, 645,  98]])

In [160]:
b= np.empty((5,3), dtype=object)

In [161]:
b

array([[None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

In [162]:
b= np.empty([2, 5, 3])

In [163]:
b

array([[[0.54471539, 0.8758534 , 0.30511157],
        [0.97831983, 0.44259971, 0.0773027 ],
        [0.16491556, 0.07543474, 0.49319018],
        [0.58711887, 0.36483401, 0.6591038 ],
        [0.49162454, 0.4247582 , 0.80700444]],

       [[0.74196961, 0.91733581, 0.33325038],
        [0.33964203, 0.61022808, 0.98016621],
        [0.92444942, 0.02923255, 0.43943279],
        [0.71418618, 0.06440454, 0.14749146],
        [0.5268325 , 0.45983494, 0.27082231]]])

In [164]:
b= np.empty([2,5,3], dtype=int)

In [165]:
b

array([[[ 323502056,        398,         67],
        [         0,          0,          0],
        [         0,          0,          0],
        [         0, 1868767867,  975332708],
        [1029841440,  779120160, 1953525093]],

       [[ 844834937,  858535212, 1679830109],
        [1701869940, 1953392957,  539763241],
        [1702389026, 1769239907, 1667198575],
        [1953396079,  824195618,    8205366],
        [         0,  540680804,    8215899]]])

In [166]:
b= np.empty([2,5,3], dtype=object)

In [167]:
b

array([[[None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None]],

       [[None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None],
        [None, None, None]]], dtype=object)

-------

## Eye Function

## The Eye Function returns a 2-D array, with 1 on diagonal and 0 eleswhere

## Syntax :
    np.eye(shape, k, dtype)
    
* Here, if only No of Rows is passed, then NO of Column = No of Rows
* K is index of diagonal, by default k = 0 means Main diagonal ; when k=positive means Upper diagonal ; when k=neagtibve means Lower diagonal
* The default datatype is float

In [168]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [169]:
np.eye(4, k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [170]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [171]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [172]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [173]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [174]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [175]:
np.eye(1)

array([[1.]])

In [176]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [177]:
np.eye(6,9, k=3, dtype=int)

array([[0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [178]:
np.eye(5, dtype=str)

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [179]:
np.eye(5, dtype=str).ndim

2

------------

# Identity Function

#### It returns an identity array i.e., a square array with 1 on the main diagonal and all other elements are 0.

###### Syntax :
    np.identity(shape, dtype)

- It takes a single integer value only as shape.
- The No. of Rows and No. of Columns will be equal to the given integer value.
- The default datatype is float

In [180]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [181]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [182]:
np.identity(4, dtype=int).ndim

2

In [183]:
np.identity(4, dtype=int).shape

(4, 4)

In [184]:
np.identity(4, dtype=int).size

16

In [185]:
np.identity(4, dtype=str)

array([['1', '', '', ''],
       ['', '1', '', ''],
       ['', '', '1', ''],
       ['', '', '', '1']], dtype='<U1')

In [186]:
a = np.identity(4, dtype=int)

In [187]:
a*3

array([[3, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [188]:
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [189]:
a*2.5

array([[2.5, 0. , 0. , 0. ],
       [0. , 2.5, 0. , 0. ],
       [0. , 0. , 2.5, 0. ],
       [0. , 0. , 0. , 2.5]])

----------

#### Ones Like Array - It returns an array of Ones, with the same shape & type as of the given array.

#### Syntax :
    np.ones_like(array, dtype)

In [190]:
a = np.array([21,52,93])

In [191]:
a

array([21, 52, 93])

In [192]:
b= np.ones_like(a)

In [193]:
b

array([1, 1, 1])

In [194]:
c = np.random.random((3,4))

In [195]:
c

array([[0.09558568, 0.21359302, 0.30293149, 0.39230557],
       [0.99910794, 0.91790911, 0.36140746, 0.7427031 ],
       [0.02409742, 0.32434014, 0.68608648, 0.99540367]])

In [196]:
np.ones_like(c)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [197]:
np.ones_like(c, dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

-------

#### Zeros Like Array - It returns an array of Zeros, with the same shape & type as of the given array.

#### Syntax :
    np.zeros_like(array, dtype)

In [198]:
a

array([21, 52, 93])

In [199]:
np.zeros_like(a)

array([0, 0, 0])

In [200]:
b = np.random.randn(5,2)

In [201]:
b

array([[ 1.06050135, -0.37232564],
       [-0.34221273, -0.1568148 ],
       [ 1.01882926,  0.56702726],
       [-0.14185031,  0.49611005],
       [ 0.2127774 ,  0.53201639]])

In [202]:
np.zeros_like(b)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [203]:
np.zeros_like(b, dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

-------------------

#### Full Like Array - It returns a full array of Constant element, with the same shape & type as of the given array.

#### Syntax :
    np.full_like(array, fill_value, dtype)

In [204]:
a

array([21, 52, 93])

In [205]:
np.full_like(a, 7)

array([7, 7, 7])

In [206]:
c = np.random.randn(2,3,4)

In [207]:
c

array([[[ 0.02377853,  0.21807651,  0.77207401,  0.68076235],
        [ 0.309474  , -0.36808385,  0.6959875 ,  1.31452324],
        [-0.43563099,  1.37728084, -0.79228115,  0.54121978]],

       [[-0.35116014,  0.70830243,  0.62288634, -0.77619089],
        [ 0.83353328, -0.06688272,  0.85237887,  1.20283884],
        [-0.30305979,  1.66647659,  0.57923742, -1.02830609]]])

In [208]:
np.full_like(c, 71)

array([[[71., 71., 71., 71.],
        [71., 71., 71., 71.],
        [71., 71., 71., 71.]],

       [[71., 71., 71., 71.],
        [71., 71., 71., 71.],
        [71., 71., 71., 71.]]])

In [209]:
np.full_like(c, 71, dtype = int)

array([[[71, 71, 71, 71],
        [71, 71, 71, 71],
        [71, 71, 71, 71]],

       [[71, 71, 71, 71],
        [71, 71, 71, 71],
        [71, 71, 71, 71]]])

In [210]:
np.full_like(c, -71, dtype = int)

array([[[-71, -71, -71, -71],
        [-71, -71, -71, -71],
        [-71, -71, -71, -71]],

       [[-71, -71, -71, -71],
        [-71, -71, -71, -71],
        [-71, -71, -71, -71]]])

-------------

## Diagonal Function - It is used to extract the diagonal elements of an array, or , used to construct a new diagonal array

#### Syntax :
    np.diag(a, k)

#### Note :
- If 'a' is a 2-D array, it extracts the diagonal elements. 
- If 'a' is a 1-D array, it constructs a 2-D array with elements of 'a' on diagonal.
- By default, k is 0. Use k>0 for diagonals above the main diagonal. Use k<0 for diagonals below the main diagonal.

In [211]:
np.diag(a)

array([[21,  0,  0],
       [ 0, 52,  0],
       [ 0,  0, 93]])

In [212]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [213]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [214]:
a.ndim

2

In [215]:
np.diag(a)

array([1, 5, 9])

In [216]:
b = np.array([1,2,3,4,5])

In [217]:
b

array([1, 2, 3, 4, 5])

In [218]:
b.ndim

1

In [219]:
np.diag(b)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [220]:
np.diag(b).ndim

2

In [221]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [222]:
np.diag(a, k=0)

array([1, 5, 9])

In [223]:
np.diag(a, k=1)

array([2, 6])

In [224]:
np.diag(a, k=2)

array([3])

In [225]:
np.diag(a, k=-1)

array([4, 8])

In [226]:
b

array([1, 2, 3, 4, 5])

In [227]:
np.diag(b, k=0)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [228]:
np.diag(b, k=2)

array([[0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [229]:
np.diag(b, k=-1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

-----------

## Transpose Function - It converts the Rows into Columns, and Columns into Rows

#### Syntax
    array.T
    or,
    np.transpose(array)

In [230]:
import numpy as np

#### Transpose of a 2-D array

In [231]:
a= np.array([[1,2,3],[4,5,6]])

In [232]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [233]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [234]:
a.shape

(2, 3)

In [236]:
a.T.shape

(3, 2)

In [237]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Transpose of a 1-D array

In [238]:
b = np.array([11,12,13,14,15,16])

In [239]:
b

array([11, 12, 13, 14, 15, 16])

In [240]:
b.T

array([11, 12, 13, 14, 15, 16])

In [241]:
b.shape

(6,)

In [242]:
b.T.shape

(6,)

------------

## Transpose of a 3-D array

In [243]:
c= np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [244]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [245]:
c.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [246]:
c.shape

(1, 3, 3)

In [247]:
c.T.shape

(3, 3, 1)

-------------

### Unary Operators - Those operators that require only one operand.


These functions can be applied row-wise or column-wise by setting an 'axis' parameter

Suppose 'a' is an array

a.max() ,  a.max(axis=1) , a.max(axis=0) , a.sum()
a.min() ,  a.min(axis=1) , a.min(axis=0) , np.sum(a, axis=1)

In [248]:
a = np.array([1,12,35,49])

In [249]:
a

array([ 1, 12, 35, 49])

In [251]:
a.max()

49

In [252]:
a.min()

1

In [253]:
a.sum()

97

In [254]:
b = np.array([[1,23,45],[56,39,91]])

In [255]:
b

array([[ 1, 23, 45],
       [56, 39, 91]])

In [256]:
b.max()

91

In [258]:
b.max(axis=1)

array([45, 91])

In [259]:
b.max(axis=0)

array([56, 39, 91])

In [260]:
b.min()

1

In [261]:
b.min(axis=1)

array([ 1, 39])

In [262]:
b.min(axis=0)

array([ 1, 23, 45])

In [263]:
b.sum()

255

In [264]:
b.sum(axis=0)

array([ 57,  62, 136])

In [265]:
b.sum(axis=1)

array([ 69, 186])

In [266]:
c = np.arange(18)

In [267]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [268]:
c = np.arange(18).reshape(2,3,3)

In [269]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [270]:
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [271]:
c.max()

17

In [272]:
c.min()

0

In [273]:
c.max(axis=1)

array([[ 6,  7,  8],
       [15, 16, 17]])

In [274]:
c.max(axis=0)

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [276]:
c.min(axis=1)

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [277]:
c.min(axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [278]:
c.sum()

153

In [279]:
c.sum(axis=1)

array([[ 9, 12, 15],
       [36, 39, 42]])

In [280]:
c.sum(axis=0)

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

----------

## Vstack or Hstack is used to combine two or more arrays to form a new array.

- Vstack - Combine the arrays vertically.
- Hstack - Combine the arrays horizontally.

### In 1-D Ary

In [281]:
a = np.array([1,2,3,4,5])

In [282]:
a

array([1, 2, 3, 4, 5])

In [283]:
b = np.array([6,7,8,9,10])

In [284]:
b

array([ 6,  7,  8,  9, 10])

In [285]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [287]:
np.vstack((a,b)).ndim

2

In [286]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [288]:
np.hstack((a,b)).ndim

1

## In 2-D array

In [289]:
p = np.array([[1,2,3,4],[5,6,7,8]])

In [290]:
p

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [291]:
q = np.array([[9,10,11,12],[13,14,15,16]])

In [292]:
q

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [294]:
v = np.vstack((p,q))

In [295]:
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [296]:
v.ndim

2

In [297]:
h = np.hstack((p,q))

In [298]:
h

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [299]:
h.ndim

2

## In 3-D array

In [300]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [301]:
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [302]:
y = np.array([[[10,11,12],[13,14,15],[16,17,18]]])

In [303]:
y

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [304]:
np.vstack((x,y))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [305]:
np.vstack((x,y)).ndim

3

In [306]:
np.hstack((x,y))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [307]:
np.hstack((x,y)).ndim

3

In [308]:
np.hstack((x,y)).shape

(1, 6, 3)

In [310]:
np.vstack((x,y)).shape

(2, 3, 3)

------------

### Indexing is used to obtain particular element(s) or row(s) or column(s) from the numpy array(s)

Here, we pass the Index of the element to access it

The Index starts from 0, not from 1

It returns elements till "stop index - 1" index

#### Indexing in 1-D Array

Format : array[start index : stop index]

In [313]:
a = np.array([1,22,34,46,58])

In [314]:
a

array([ 1, 22, 34, 46, 58])

In [315]:
a[0]

1

In [317]:
a[3]

46

In [318]:
a[:]

array([ 1, 22, 34, 46, 58])

In [319]:
a[0:]

array([ 1, 22, 34, 46, 58])

In [321]:
a[-1]

58

In [322]:
a[2:]

array([34, 46, 58])

In [323]:
a[:1]

array([1])

In [324]:
a[:5]

array([ 1, 22, 34, 46, 58])

In [326]:
a[:4]

array([ 1, 22, 34, 46])

In [327]:
a[1:2]

array([22])

In [328]:
a[2:-1]

array([34, 46])

In [330]:
a.T[2]

34

# Indexing in 2-D array

In [335]:
a = np.array([[11,12,13,14],[15,16,17,18]])

In [336]:
a

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [337]:
a[0]

array([11, 12, 13, 14])

In [339]:
a[1]

array([15, 16, 17, 18])

In [340]:
a[:]

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [341]:
a[0 , 1:2]

array([12])

In [342]:
a[1, 2:3]

array([17])

In [343]:
a[a>14]

array([15, 16, 17, 18])

In [344]:
 a[a<16] 

array([11, 12, 13, 14, 15])

------------

## Indexing in 3-D array

In [358]:
c = np.arange(18).reshape(2,3,3)

In [359]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [360]:
c[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [361]:
c[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [363]:
c[:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [365]:
c[0, 1:3, :]

array([[3, 4, 5],
       [6, 7, 8]])

In [366]:
c[c<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [367]:
c[1,1:2,1:2]

array([[13]])

In [368]:
c[1,1:2,:]

array([[12, 13, 14]])

In [370]:
c[1, : , 1:3]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [373]:
c[0, : , 0:1]

array([[0],
       [3],
       [6]])

In [375]:
c[1,2,1]

16

---------------

Any & All functions are built-in functions.

These functions works on comparision basis.

Any function - It returns True, if any element satisfy the given condition. It uses logical OR operator.

Syntax : np.any( condition )

All function - It returns True, if all elements satisfy the given condition. It uses logical AND operator.

Syntax : np.all( condition )

In [381]:
q = np.random.randint(10,1000,15)

In [382]:
q

array([ 32, 313, 307, 450,  12, 678, 974, 575,  50, 390,  27, 492, 121,
        46, 688])

In [383]:
np.any(q == 500)

False

In [384]:
np.any(q == 307)

True

In [385]:
np.any(q<100)

True

In [386]:
np.any(q>1000)

False

In [387]:
q

array([ 32, 313, 307, 450,  12, 678, 974, 575,  50, 390,  27, 492, 121,
        46, 688])

In [388]:
np.all(q==500)

False

In [389]:
np.all(q<100)

False

In [390]:
np.all(q<1000)

True

In [391]:
np.all(q<500)

False

In [392]:
print(np.all(q<1000))

True
